version: '3'

services:
    nginx:
        container_name : ${COMPOSE_PROJECT_NAME}-${WEB_SERVER_TYPE}
        build:
            context: ./bin/${WEB_SERVER_TYPE}
        links:
            - php
        depends_on:
            - php
        volumes:
            - ./www/bitrix:/home/www/bitrix
            - ./log/container-nginx:/home/log/nginx
        ports:
            - ${INTERFACE}:${HOST_MACHINE_UNSECURE_HOST_PORT}:${HOST_MACHINE_UNSECURE_HOST_PORT_OPEN}
            - ${INTERFACE}:${HOST_MACHINE_SECURE_HOST_PORT}:${HOST_MACHINE_SECURE_HOST_PORT_OPEN}
        networks:
            - ${COMPOSE_PROJECT_NAME}
        restart: always
    php:
        container_name: ${COMPOSE_PROJECT_NAME}-${PHP_VERSION}
        build:
            context: ./bin/${PHP_VERSION}
        links:
            - mysql
            - memcached
        depends_on:
            - mysql
            - memcached
        volumes:
            - ./www/bitrix:/home/www/bitrix

        networks:
            - ${COMPOSE_PROJECT_NAME}
        restart: always
    mysql:
        container_name:  ${COMPOSE_PROJECT_NAME}-${DB_SERVER_TYPE}
        build:
            context: ./bin/${DB_SERVER_TYPE}
        volumes:
            - chisto-site-mysql:/home/lib/mysql
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - "${INTERFACE}:${HOST_MACHINE_MYSQL_PORT}:${HOST_MACHINE_MYSQL_PORT_OPEN}"
        networks:
            - ${COMPOSE_PROJECT_NAME}
        restart: always


volumes:
    chisto-site-mysql:
        driver: local
networks:
    test:
        driver: bridge
        driver_opts:
            com.docker.network.driver.mtu: 1450
