version: '3'

services:
  php:
    container_name: ${COMPOSE_PROJECT_NAME}-${PHP_VERSION}
    build:
      context: ./bin/${PHP_VERSION}
      dockerfile: ./Dockerfile
    links:
      - database
    depends_on:
      - database
    volumes:
      - ./www/bitrix:/home/bitrix/www # Вынести в env
      - ${LOG_PATH_PHP_LOCAL}:${LOG_PATH_PHP_CONTAINER}
    restart: unless-stopped
  database:
    container_name: ${COMPOSE_PROJECT_NAME}-${DB_SERVER_TYPE}
    build:
      context: ./bin/${DB_SERVER_TYPE}
      dockerfile: ./Dockerfile
    volumes:
      - ./data/mysql:/var/lib/mysql # Вынести в env
      - ${LOG_PATH_DATABASE_LOCAL}:${LOG_PATH_DATABASE_CONTAINER}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: password
    ports:
      - ${INTERFACE}:${HOST_MACHINE_MYSQL_PORT}:${HOST_MACHINE_MYSQL_PORT_OPEN}
    restart: unless-stopped



